export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'; //ALL PRODUCTS
export const FETCH_PRODUCT = 'FETCH_PRODUCT'; //SPECIFIC PRODUCT

export const FETCH_FARMS = 'FETCH_FARMS'; //ALL FARMS
export const FETCH_FARM = 'FETCH_FARM'; //SPECIFIC FARM

export const FETCH_USERS = 'FETCH_USERS'; //ALL USERS

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; //LOGS IN USER AND GRABS SESSION ID
export const REGISTER_SUCCESS = 'LOGIN_SUCCESS'; // REGISTERS USER AND GRABS SESSION ID
export const LOGOUT_SUCCESS = 'LOGIN_SUCCESS'; //LOGS OUT USER AND DELETES SESSION

export const USER_LOADING = 'USER_LOADING'; // CHECKS TO SEE IF USER IS LOADING
export const USER_LOADED = 'USER_LOADED'; // USER HAS BEEN LOADED
